### ISSUE TITLE
Quesiton about the Bayesian NN implementation

### ISSUE THREAD

**Issue by Habush** [ruqizhang/discrete-langevin#1]
Hi,

I'm going through the code for the BayesianNN implementation, and in the constructor there is `num_particles` argument https://github.com/ruqizhang/discrete-langevin/blob/97bc36960676a5314016540b7027ae3f51ff4a80/BinaryBNN/bayesian_nn.py#L47 . 

I don't understand what is the purpose of this argument. Is it a way of training the NN before re-sampling `theta` from its distribution?

P.S : Thank you sharing the code for this great work! (I'm going through the code to port it to JAX)

**Comment by gnobitab** [comment]
Hi Habush,

We use multi-chain langevin dynamics (running multiple langevin dynamics in parallel) to fully leverage the GPU. To do this, we randomly initialize num_particles networks and run Langevin dynamics with these networks independently.

**Comment by Habush** [comment]
That makes sense. Thanks for the response!
