### ISSUE TITLE
Can I confirm this line of code?

### ISSUE THREAD

**Issue by weitliu** [ruqizhang/discrete-langevin#3]
Hello. Thank you for the great work. I am just wondering if you can confirm, in https://github.com/ruqizhang/discrete-langevin/blob/99c30190f09ff593aaebffdcbabafcfb5a73d34b/CategoricalExample/samplers.py#L68, we still use grad (instead of grad_delta) to compute the grad_delta_cur? May I ask what could be the difference if I use grad_delta to get grad_delta_cur? Thank you!

**Comment by gnobitab** [comment]
grad_delta_cur means 'current delta of the gradient'. In MH, we are implementing Eq. (3) in the paper. grad_delta_cur should be from grad, not from grad_delta, because, grad_delta is the gradient of U(theta') but we want to use the gradient of U(theta).
